<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{

    public function getPorEmpresa($q, $limit)
    {
        $qb = $this->createQueryBuilder('cliente')
            ->andWhere("cliente.nombre LIKE :q")
            ->setParameter('q', "%$q%")
            ->andWhere('cliente.activo = true')
            ->orderBy('cliente.nombre')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
