<?php

namespace AppBundle\Repository;

/**
 * CostoEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostoEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
