<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{

    public function getEmpresasPorPersona($persona)
    {
        $qb = $this->createQueryBuilder('empresa')
            ->innerJoin("empresa.personas", "personas")
            ->andWhere("personas.activo = true")
            ->andWhere("personas.persona = :persona")
            ->setParameter("persona", $persona)
        ;

        return $qb->getQuery()->getResult();

    }
}
