<?php

namespace AppBundle\Repository;

/**
 * PrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
