<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{

    public function getActivos($q, $limit)
    {
        $qb = $this->createQueryBuilder('producto')
            ->andWhere("producto.nombre LIKE :q")
            ->setParameter('q', "%$q%")
            ->andWhere('producto.activo = true')
            ->orderBy('producto.nombre')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function getListado($filters, $empresa)
    {
        $qb = $this->createQueryBuilder('producto')
//            ->andWhere("producto.empresa = :empresa")
//            ->setParameter("empresa", $empresa)
        ;
        ;
        if (isset($filters["nombre"])) {
            $q = $filters["nombre"];
            $qb->andWhere("producto.nombre LIKE :q")
                ->setParameter('q', "%$q%");
        }


        return $qb->getQuery()->getResult();
    }
}
