<?php

namespace AppBundle\Repository;

/**
 * RepartidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartidorRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRepartidoresActivos()
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.activo = true');

        return $qb->getQuery()->getResult();
    }
}
