<?php

namespace AppBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByUsuario($user)
    {
        $qb = $this->createQueryBuilder("rol")
            ->innerJoin("rol.rolesUsuario", "rolesUsuario")
            ->andWhere("rolesUsuario.activo = true")
            ->andWhere("rolesUsuario = :usuario")
            ->setParameter("usuario", $user);


        return $qb->getQuery()->getResult();

    }


}
