<?php

namespace AppBundle\Repository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRouteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRouteNotInRol($ids, $rol)
    {

        if (is_array($ids)) {
            $ids = implode($ids, ', ');
        }

        $qb = $this->createQueryBuilder('rr')
            ->innerJoin("rr.route", "route")
            ->andWhere("rr.rol = :rol ")
            ->andWhere("route.id NOT IN ($ids)")
            ->andWhere("rr.activo = true")
            ->setParameter("rol", $rol);

        return $qb->getQuery()->getResult();

    }
}
