<?php

namespace AppBundle\Repository;

/**
 * SectorMesaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorMesaRepository extends \Doctrine\ORM\EntityRepository
{

}
