imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@UsuariosBundle/Resources/config/services.yml" }
    - { resource: "@UtilBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    app.path.personas_image: /uploads/images/personas
    app.path.productos_image: /uploads/images/productos
    app.path.empresas_image: /uploads/images/empresas



framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_name: %site_name%
        version: %version%
    form_themes:
        - 'AppBundle:Form:custom_widgets.html.twig'
        - 'AppBundle:Form:image_widget.html.twig'
        - 'UtilBundle:Form:fields.html.twig'
#        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
#        - 'vich_fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UsuariosBundle\Entity\Usuario
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

#doctrine extentions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            translatable: true
            timestampable: true
            blameable: true
            sluggable: true

#vich uploader
vich_uploader:
    db_driver: orm
    mappings:
        image_empresa:
                    uri_prefix:         %app.path.empresas_image%
                    upload_destination: %kernel.root_dir%/../web/uploads/images/empresas
                    namer:              vich_uploader.namer_origname
        image_persona:
            uri_prefix:         %app.path.personas_image%
            upload_destination: %kernel.root_dir%/../web/uploads/images/personas
            namer:              vich_uploader.namer_origname
        image_producto:
                    uri_prefix:         %app.path.productos_image%
                    upload_destination: %kernel.root_dir%/../web/uploads/images/productos
                    namer:              vich_uploader.namer_origname


#fos rest
fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_converter:
        enabled: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            # ... previous rules declarations
#            - { path: '^/admin', stop: true }  # <-- add this line
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

bazinga_geocoder:
  providers:
    nominat:
      factory: Bazinga\GeocoderBundle\ProviderFactory\NominatimFactory

tetranz_select2_entity:
    minimum_input_length: 2
    page_limit: 8
#    allow_clear: true
#    delay: 500
#    language: es
#    cache: false
#    cache_timeout: 0
#    scroll: true