usuarios:
    path:     /
    defaults: { _controller: "UsuariosBundle:Usuario:index" }

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "UsuariosBundle:Usuario:show" }

usuarios_new:
    path:     /new
    defaults: { _controller: "UsuariosBundle:Usuario:new" }

usuarios_create:
    path:     /create
    defaults: { _controller: "UsuariosBundle:Usuario:create" }
    methods:  POST

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "UsuariosBundle:Usuario:edit" }

usuarios_update:
    path:     /{id}/update
    defaults: { _controller: "UsuariosBundle:Usuario:update" }
    methods:  [POST, PUT]

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "UsuariosBundle:Usuario:delete" }
    methods:  [POST, DELETE]

usuarios_persona_new:
    path:     /persona/new/{id}
    defaults: { _controller: "UsuariosBundle:Usuario:newPersona" }

usuarios_persona_create:
      path:     /persona/create
      defaults: { _controller: "UsuariosBundle:Usuario:createPersona" }
      methods:  POST

fos_user_change_password:
    path:     /change-password
    defaults: { _controller: "UsuariosBundle:ChangePassword:changePassword" }
    methods:  [GET, POST]

#fos_user_resetting_request:
#    path:     /request
#    defaults: { _controller: "UsuariosBundle:Resetting:request" }
#    methods:  [GET]

fos_user_resetting_reset:
    path:     /reset/{token}
    defaults: { _controller: "UsuariosBundle:Resetting:reset" }
    methods:  [GET, POST]
