parameters:
#    util.example.class: UtilBundle\Example

services:
    form.type.jqueryautocomplete:
        class: UtilBundle\Form\Type\JqueryAutocompleteType
        autowire: true
#        autoconfigure: true
#        public: true
#        arguments:
#            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: jqueryautocomplete }

    tetranz_select2entity.select2entity_type:
        class: UtilBundle\Form\Type\Select2EntityType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "2"
            - "8"
            - "json"
        tags:
            - { name: form.type, alias: tetranz_select2entity }

    form.type.bootstrapcollection:
        class: UtilBundle\Form\Type\BootstrapCollectionType
#        arguments:
#            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: bootstrapcollection }

            
    form.type.jqueryautocompletetext:
        class: UtilBundle\Form\Type\JqueryAutocompleteTextType
        tags:
            - { name: form.type, alias: jqueryautocompletetext }
            
#    excel.tool:
#            class: UtilBundle\Services\ExcelTool
#            arguments:
#                phpexcel: "@phpexcel"
#                entityManager: "@doctrine.orm.entity_manager"
#            tags:
#                - { name: excel.tool, alias: excel.tool }

    form.type.verticalcollection:
        class: UtilBundle\Form\Type\VerticalCollectionType
#        arguments:
#            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: verticalcollection }
    app.twig_extension:
        class: UtilBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

