services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Services\:
        resource: '../../Services'
        tags: ['controller.service_arguments']
