<?php

namespace AppBundle\Entity;

/**
 * PersonaEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
